from .exp import INDATED

if INDATED:

    FPS = 3
    PADDING = 10

    GAME_WIDTH = 1620   # 590 (-> 768) + 768 => 1536
    GAME_HEIGHT = 963   # 221 (-> 287) + 256 => 543

    MENU_WIDTH = 250
    MENU_HEIGHT = 963

    GRID_ROWS = 18
    GRID_COLS = 9

    GRID_WIDTH  = GAME_WIDTH  // GRID_ROWS
    GRID_HEIGHT = GAME_HEIGHT // GRID_COLS

    WINDOW_NAME = "CATCH THE CASHFLOW"
    WINDOW_WIDTH = GAME_WIDTH + MENU_WIDTH + PADDING * 7
    WINDOW_HEIGHT = max(GAME_HEIGHT, MENU_HEIGHT) + PADDING * 3

else:
    FPS = 1000
    PADDING = 10

    GAME_WIDTH = 1620   # 590 (-> 768) + 768 => 1536
    GAME_HEIGHT = 963   # 221 (-> 287) + 256 => 543

    MENU_WIDTH = 250
    MENU_HEIGHT = 963

    GRID_ROWS = 9
    GRID_COLS = 18

    GRID_WIDTH  = GAME_WIDTH  // GRID_ROWS
    GRID_HEIGHT = GAME_HEIGHT // GRID_COLS

    WINDOW_NAME = "CATCH ME IF YOU CAN"
    WINDOW_WIDTH = GAME_WIDTH + MENU_WIDTH + PADDING * 7
    WINDOW_HEIGHT = max(GAME_HEIGHT, MENU_HEIGHT) + PADDING * 3
